### ISSUE TITLE
App can't be started

### ISSUE THREAD

**Issue by joekerna** [nextcloud/admin_notifications#10]
### Steps to reproduce
1. Sadly not possible. Seems random

### Expected behaviour
App should be activated when clicking on activate

### Actual behaviour
When clicking on activate I get the error message (translated from German): 

> Error: This application can not be activated, because it would cause instability to the server

### Server configuration

**Operating system**: Ubuntu 17.04

**Web server:** Nginx 1.12

**Database:** MySQL 5.7.17

**PHP version:** 7.1.4

**Nextcloud version:** 11.0.3 RC3

**Where did you install Nextcloud from:** Nextcloud website

### Client configuration
**Browser:** Firefox 45.8.0 ESR

**Operating system:** Windows 10

**Comment by joekerna** [comment]
I just got the same error for the Preview Generator app. So this might be the wrong place for this issue?!

**Comment by nickvergessen** [comment]
Can you check whether there is something in your Nextcloud.log file?
Sounds very suspicious and there should be something in the log.

**Comment by joekerna** [comment]
Exception: The requested uri(/settings/admin/index.php/apps/logreader/settings) cannot be processed by the script '/apps/logreader/settings')

    /var/www/nextcloud/lib/base.php - line 962: OC\AppFramework\Http\Request->getRawPathInfo()
    /var/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}



Exception: The requested uri(/settings/admin/ocs/v2.php/apps/notifications/api/v2/notifications) cannot be processed by the script '/apps/notifica')

    /var/www/nextcloud/lib/base.php - line 962: OC\AppFramework\Http\Request->getRawPathInfo()
    /var/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}

**Comment by joekerna** [comment]
I think the problem was due to a mistake in my Nginx setup which caused PHP-FPM to fail randomly and cause 502 errors.
After fixing the mistake my random 502 errors are gone and activating apps is working fine.
For me this issue can be closed. We could talk about providing an error message that points towards those 502 errors?!
