### ISSUE TITLE
Ability to push messages to NC user from external source

### ISSUE THREAD

**Issue by jkaberg** [nextcloud/admin_notifications#13]
Repost of https://github.com/nextcloud/notifications/issues/83

Perhaps implement it in the same manner as user app password where one could revoke tokens aswell. That way one could generate an token per service. 

Something like this would be nice:
```
curl -X POST \
  https://<server-url>/ocs/v2.php/apps/admin_notifications/api/v1/notifications/<user-id>/<token> \
  -d "shortMessage=<short-message>" \
  -d "longMessage=<long-message>"
```

**Comment by nickvergessen** [comment]
You mean instead of an admin tool any user should be able to use this endpoint to spam themselves?

**Comment by jkaberg** [comment]
@nickvergessen yes pretty much, just think of [Pusbullet](https://www.pushbullet.com/) or [Pushover](https://pushover.net/) but self hosted utilizing existing and possibly new infrastructure/code (server, mobile apps etc.)

Imagine doing something like the "app passwords" functionally which already exist in NC but instead the user generates an token which could be used to send notifications to himself. For instance I would generate an token to use with service Xy, at Service Xy I register an webhook to post an notification to an Nextcloud endpoint (see OP) which would then notify me on all platforms I use Nextcloud with (web, android, desktop).

**Comment by nickvergessen** [comment]
Because this app is merged into notifications, I'm reopening https://github.com/nextcloud/notifications/issues/83 instead. Sorry for the trouble.
