### ISSUE TITLE
Possibility to open an app, on Click on the Notification from the WebInterface

### ISSUE THREAD

**Issue by ghost** [nextcloud/admin_notifications#14]
Hi,

[EDIT, can be closed ...]
I am really sorry, I did't try to make a html link on it before ... I can make what I want with a simple "a" tag.
But, I got a second request, it should be great if, on the same way, we can select an other icon for the display of the notification.

By the way, thank for your product, it is really helpfull (and I'm sorry for my bad english),
David

**Comment by nickvergessen** [comment]
Well you can do all that by implementing a notifier in your own app.
This app is ment to be a simple example of the API mostly for testing.

You can abuse the app for several other things, but I'm not going to add more features to this tiny tool.

You can either clone this app or write a notifier from scratch: https://github.com/nextcloud/notifications/blob/master/docs/notification-workflow.md

**Comment by ghost** [comment]
First, thank you for this quick reply.
I understand, but, I just need one little modification on your source code to make what I want if I add data directly on the db.

Replace the line 72 on file "lib/Notification/Notifier.php":
`if($notification->getIcon()=="") $notification->setIcon($this->urlGenerator->getAbsoluteURL($this->urlGenerator->imagePath(Application::APP_ID, 'app-dark.svg')));`

I don't want to create a full new app for only that little thing.
Do you think it possible to add this condition in your app ?
