### ISSUE TITLE
Add an admin interface

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/admin_notifications#6]
As requested by @Schmuuu in https://github.com/nextcloud/admin_notifications/issues/5#issuecomment-284998615

**Comment by stratege1401** [comment]
Nice tools, but yes, missing the GUI side ( lazzzzzy this time ... putty ssh access is so not cool :) )

**Comment by nickvergessen** [comment]
Moved to https://github.com/nextcloud/notifications/issues/122
