### ISSUE TITLE
Notifications for Mobile Applications (iOS & Android)

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/admin_notifications#7]
Hi, 
Notifications for mobile app at same time, Is this possible?

**Comment by nickvergessen** [comment]
Yes, ios and android are working on notifications atm.

**Comment by emresaracoglu** [comment]
That's good but I have tried and my phone (iOS - Nextcloud v2.16) notification not received.

**Comment by emresaracoglu** [comment]
That's good but I have tried and my phone (iOS - Nextcloud v2.16) notification not received.

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/ios/issues/54 for iOS progress ;)

**Comment by emresaracoglu** [comment]
Could you give us information about the issue? I think it was temporarily canceled.

@nickvergessen

**Comment by nickvergessen** [comment]
You mean for iOS?

Please comment in the iOS app then, I have no further input and dont know if it is working or not, since im not using iOS

**Comment by emresaracoglu** [comment]
I see, thank you.

@nickvergessen
